{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "restic-rados-server.networkPolicyName" . }}
  labels:
    {{- include "restic-rados-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "restic-rados-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.services }}
    []
    {{- else }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- end }}
{{- range $name, $service := .Values.services }}
{{- $ingressFrom := dig "networkPolicy" "ingressFrom" (list) $service }}
{{- with $ingressFrom }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "restic-rados-server.serviceName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "restic-rados-server.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "restic-rados-server.selectorLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- toYaml . | nindent 8 }}
      ports:
        - protocol: TCP
          port: {{ int $service.targetPort }}
{{- end }}
{{- end }}
{{- end }}
